### ISSUE TITLE
AssertionError assert(torch.min(y.data) >= -1)

### ISSUE THREAD

**Issue by Truong-Thanh-Quang** [Deepest-Project/Transformer-TTS#19]
I ran python3 prepare_data.py with my own data (22050, 16bit, mono), AssertionError occured.

HBox(children=(FloatProgress(value=0.0, max=28825.0), HTML(value='')))
Traceback (most recent call last):
  File "prepare_data.py", line 103, in <module>
    text, char_seq, phone_seq, melspec, wav = save_file(k)
  File "prepare_data.py", line 85, in save_file
    melspec, wav = get_mel(wav_name)
  File "prepare_data.py", line 75, in get_mel
    melspec = stft.mel_spectrogram(wav.unsqueeze(0))
  File "/works/Transformer-TTS/layers.py", line 72, in mel_spectrogram
    assert(torch.min(y.data) >= -1)
AssertionError

Should I normalize wave data array into range [-1,1] before pass the array to FloatTensor in get_mel() function?

def get_mel(filename):
    wav, sr = librosa.load(filename, sr=22050)
    wav = torch.FloatTensor(wav.astype(np.float32))
    melspec = stft.mel_spectrogram(wav.unsqueeze(0))

**Comment by Jackson-Kang** [comment]
Hi, quangtt2016

I think that the preprocessing codes in this project are originally from Tactoron2 written by NVIDIA.

If you see the line #43 in the link, the audio values are divided by their maximum value. 
https://github.com/NVIDIA/tacotron2/blob/master/data_utils.py
Unfortunately, this code is not written in the preprocessing codes in this repos.

Plus, when you store preprocessed mel-spectrograms, plz normalize them so that they are ranged to [-max_value, mav_value]. In Deeplearning, normalization of input values are very crucial due to stable training and fast convergence.

Hope that my comment is helpful to you.

Sincerely,
